### ISSUE TITLE
Port 0 is accepted as a valid port

### ISSUE THREAD

**Issue by kiavash-at-work** [ashuio/shavee#1]
Passing `-P 0` argument should raise error and not be accepted.

**Comment by kiavash-at-work** [comment]
Initiated PR #3 to fix port 0 and an example of unit tests.

**Comment by ashuio** [comment]
Right now the behavior is that port 0 is redirected to the default port of that service

so if i pass `-P 0` with an https link it will redirect it to port 443

Should i change that?

**Comment by kiavash-at-work** [comment]
Having a default port for the transports is a good idea, however I would recommend to borrow the idea from `ssh` or `ftp` and if the port is not eliminated from the command line, then the default port number for each transport protocol is used, instead of using port 0 (which is reserved by IANA and technically invalid for our purposes) should be rejected.

**Comment by ashuio** [comment]
I think you're right, Thanks for the PR let me merge it.
