### ISSUE TITLE
[Feature Request] Max Limit for file used for hashing

### ISSUE THREAD

**Issue by kiavash-at-work** [ashuio/shavee#10]
Currently, there is no upper for the size of the file using to generate hash. If this file is small, the hash is generated quite fast however as it grows, it takes longer. For example, the program never exits if this command `shavee -f /dev/zero` is executed, because `/dev/zero` has no `EOF`. While this doesn't seem to be a safe usage of the program, it demonstrate a corner case.

A potential solution is to either hardcode a max size limit or pass it as an optional argument to the program.

**Comment by ashuio** [comment]
I think hard coding a MAX size limit would be too much?

I think the user should have the freedom to choose any file they like. If they are willing to trade off time for it.

**Comment by kiavash-at-work** [comment]
I totally agree with your suggestion. `Clap` can parse [multiple values](https://docs.rs/clap/2.31.0/clap/struct.Arg.html#method.number_of_values) for one option, for example if user entered `-f <file>` then no limit for the size, but if user explicitly entered size `-f <file> <max size>` then that size is used. The corner case of `-f /dev/zero` which currently causes "softlock" then can be changed to `-f /dev/zero 1024` (just as an example) which only 1024 bytes of `/dev/zero` will be used for hash generation.

I would say this is not very high priority feature request, but I suggest to keep it open until it is implemented in future.

**Comment by ashuio** [comment]
I think this could be useful for stuff like `-f /dev/sdb 4096`  where you can use a device directly instead of a regular file.

**Comment by kiavash-at-work** [comment]
Following your suggestion, I implemented parsing SIZE as an optional argument passed after the location of file or address in this commit:

68c13e03648b7b06a5c9626e8d6b895403851f66

`size` is still not used in `filehash` generation yet, but all the "plumpings" are done from CLI argument parsing to passing `size` as a variable to `filehash`

**Comment by kiavash-at-work** [comment]
Thank you for reviewing and committing the PR #12. I think we can close this case and if there are bugs in the implemented feature open a new case.
