### ISSUE TITLE
Odd piece of code

### ISSUE THREAD

**Issue by marcaddeo** [ashuio/shavee#2]
In `main.rs` it looks like dataset passwords are being suffixed with "Aveesha". Is this a remnant from testing that should be removed? 

https://github.com/ashuio/shavee/blob/af275d00cef4a55e4c0e67047278c20cee644466/src/main.rs#L28

**Comment by kiavash-at-work** [comment]
I believe that is supposed to be an equivalent of "salt"ing the password.

**Comment by ashuio** [comment]
I believe conceptually that's how salts work haha, Please correct me if i am wrong.

**Comment by marcaddeo** [comment]
Ah, yes. I had forgotten about salts. For some reason that line just looked out of place. Maybe a comment to make it clear that it's a salt would be beneficial.

I'm not a security expert, by any means, but does having a static salt for _every_ user of this program make it less secure?

**Comment by kiavash-at-work** [comment]
I found this when searching for [Static vs random salt](https://stackoverflow.com/a/5929280)

> Random salts have a tremendous benefit. If all accounts in the system use the same salt, an attacker can brute-force calculate hashes for that salt and break into all accounts with just one computational run. If they use different salts per account, brute-force only gets you into one account.

However in this code, having a 2FA and password already feels pretty random and `pass.push_str("Aveesha"); ` seems to be helpful to assure the minimum combined password length :shrug:

**Comment by ashuio** [comment]
> Ah, yes. I had forgotten about salts. For some reason that line just looked out of place. Maybe a comment to make it clear that it's a salt would be beneficial.
> 
> I'm not a security expert, by any means, but does having a static salt for _every_ user of this program make it less secure?

Static salt helps with stuff like backups and restore even across systems, an attacker would specifically target this particular Project and with the amount of resources required, this doesn't really makes sense.
