### ISSUE TITLE
[TODO] Implement config file

### ISSUE THREAD

**Issue by kiavash-at-work** [ashuio/shavee#20]
**To parse a config file in addition to command line arguments.**

Prerequisite:
- [ ] Load and Parse Config file
- [x] Store config in `ZFS` Properties to simplify `PAM module` unlock

**Comment by ashuio** [comment]
Now with the latest commit it should be able to read and write config to ZFS properties

**Comment by ashuio** [comment]
I don't think config files would make sense now since we can use properties now.
Until we plan on features requiring config files we can close it for now.
