### ISSUE TITLE
Create minimalist version without File and network HTTP(S) / SFTP capabilites 

### ISSUE THREAD

**Issue by cmosetick** [ashuio/shavee#24]
Hello and thanks for this project. We are very interested in the Yubikey integration of shavee.

We have also been trying to evaluate what is needed for a comprehensive audit of shavee. So far we have identified the network retrieval options and possibly the File options as a potential burden/blocker with regard to 3rd party security auditing. Although we appreciate the comprehensive nature of the current implementation, we feel that a minimalist version that focuses of Yubikey would be great. 

The current Cargo.lock file is over 700 lines and imports a large number of Rust packages, including Windows 32 bit and Windows 64 bit libraries.
- `winapi-i686-pc-windows-gnu`
- `winapi-x86_64-pc-windows-gnu`
- `winapi-util`

```
[package]]
name = "termcolor"
version = "1.1.2"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "2dfed899f0eb03f32ee8c6a0aabdb8a7949659e3466561fc0adf54e26d88c5f4"
dependencies = [
 "winapi-util",
]
```

Since ZFS is primarily targeted towards *Nix systems we really want to understand why some of these libraries are being used / referenced. Or would prefer to remove them from the shavee supply chain altogether. 

We know that we have an option to fork the repository here and create our own minimalist fork. However, we invite you as the creator / primary maintainer of this project to consider creating a functional branch, or project fork that essentially focuses strictly on Yubikey integration. We believe that this will reduce the attack surface of shavee. And also reduce the overhead with regard to 3rd party security auditing.

Thanks for consideration!

**Comment by kiavash-at-work** [comment]
I highly appreciate your interest and suggestions. I would refer to @ashuio to discuss how to proceed with a minimalist version. Maybe it can be satisfied by a compile time switch in `Cargo.toml`

Regarding the current `Cargo.lock`, it was generated automatically and the `winapi` dependencies are related to the [`curl`](https://crates.io/crates/curl/0.4.38/dependencies) used for HTTP(S)/SFTP 2FA and [tempfile](https://crates.io/crates/tempfile/3.3.0/dependencies) used for preparing the temp files for the [unit and integration tests](https://github.com/ashuio/shavee/blob/f107b3cc60c5e24438cfa51edec3b9cfe9070be5/shavee-bin/src/main.rs#L105).

**Comment by cmosetick** [comment]
Hi Kiavash and thanks for the fast response. We appreciate the info you provided. We guessed that the Cargo.lock was auto generated so appreciate the confirmation.

Based on what you shared, removing the network retrieval options (curl) should also remove the winapi dependencies.

The compile time switch in Cargo.toml sounds compelling too.

**Comment by kiavash-at-work** [comment]
Hi Chris,

I just submitted a PR to @ashuio to review and merge if approved. Please note that there are some integration and units tests that are not yet implemented #21 and I appreciate it if you help by testing the new code.

BR,

**Comment by kiavash-at-work** [comment]
Hi @cmosetick,

You can try changing the [`default` features](https://github.com/ashuio/shavee/blob/737775d4889084a53f9c05d29be1e8404b6c82e6/shavee-bin/Cargo.toml#L14) in `Cargo.toml` before compiling and enable/disable the features.

Please try and close the case if this addresses your request.

Thanks,

**Comment by ashuio** [comment]
I think it's safe to close this issue as resolved now.
