### ISSUE TITLE
Request to tag current source as new release 

### ISSUE THREAD

**Issue by jasonodoom** [ashuio/shavee#25]
Hello @kiavash-at-work, I am having some trouble reaching  @ashuio so thought I'd create an issue here. I am working to satisfy a [packaging request for Shavee on Nixos  ](https://github.com/NixOS/nixpkgs/issues/216172) I am wondering if you can tag the latest release using the current source on GitHub so I can package from that? The only tagged version is alpha and doesn't contain a `Cargo.lock` which is needed.

**Comment by ashuio** [comment]
Hi @jasonodoom thanks for using my program and your intrest in packaging it, i will get on your request as soon as I can, unfortunately I don't have access to any desktop/laptop right now where i am at.

**Comment by ashuio** [comment]
Hi @jasonodoom 
We have just had a new release with significant updates.
would be interested in packaging it up?

**Comment by jasonodoom** [comment]
> Hi @jasonodoom We just had a new release with significant updates. would you be interested in packaging it up?

@ashuio of course, thanks for letting me know! I will take care of it this week.
