### ISSUE TITLE
[bug] Command line parse error

### ISSUE THREAD

**Issue by kiavash-at-work** [ashuio/shavee#7]
While testing `0.1.4` branch (9089e755a62c9585fe24b129d1e0b87200d8b20d), (most definitely `main` branch has the same bug too) I noticed that an unexpected error happens with this command line. **Only if `PAM_USER` environment variable is not set**.

```bash
$ ./shavee unexpected --pam -z testpool/testdataset
thread 'main' panicked at 'Panic! Something unexpected happened! Please help by reporting it as a bug.: NotPresent', shavee-bin/src/args.rs:198:55
```
This seems to be caused by a corner case when the binary is executed in PAM mode while passing an **`unexpected`** argument to the binary. `Clap` fails to reject it correctly.

It seems that [this section](https://github.com/ashuio/shavee/blob/9089e755a62c9585fe24b129d1e0b87200d8b20d/shavee-bin/src/args.rs#L105) causes `Clap` to replace `PAM_USER` with **`unexpected`** argument, instead of providing error for lack of the existence of `PAM_USER` environment variable.

Then [here](https://github.com/ashuio/shavee/blob/9089e755a62c9585fe24b129d1e0b87200d8b20d/shavee-bin/src/args.rs#L198) `PAM_USER` is being used while it doesn't exists and throws a Panic!

Unit test didn't catch it because it [sets](https://github.com/ashuio/shavee/blob/9089e755a62c9585fe24b129d1e0b87200d8b20d/shavee-bin/src/args.rs#L275) `PAM_USER` environment.

If the plan is that `0.1.4` branch will have a separate `libpam_shavee.so` instead of `--pam` PAM mode, then it should be better to to move `PAM_USER` validating and appending it to the dataset to this PAM module and remove it from the main binary argument.

**Comment by ashuio** [comment]
Maybe we can just and if statement checking it just before and exiting with a better error message.

This error is most likely to happen with accidental use of this argument without pam_exec.so since that takes care of setting the variable.

**Comment by kiavash-at-work** [comment]
> This error is most likely to happen with accidental use of this argument without pam_exec.so since that takes care of setting the variable.

Agreed and that is why I think it is better to fix it in libpam_shavee.so ([`impl PamServiceModule for PamShavee`](https://github.com/ashuio/shavee/blob/b3fdad765b80466b3098c565fe7035b84b4b7956/shavee-pam/src/lib.rs#L10)) and totally remove the `--pam` option from the main `shavee-bin` binary.

**Comment by ashuio** [comment]
Agreed, This PAM option will be removed in the 0.1.4 release.

**Comment by ashuio** [comment]
The basic layout of the Project is done so i if you wanna contribute anything you can PR to that branch now

Thanks

**Comment by kiavash-at-work** [comment]
Thanks... I will continue implementing the unit tests, before propping some major changes. For now we can keep this bug open until it is fixed in the future.

If you are interested to read more of why unit tests are important, check [this out](https://testing.googleblog.com/2009/07/by-shyam-seshadri-nowadays-when-i-talk.html).

**Comment by kiavash-at-work** [comment]
Hi @ashuio,

Please take a look at the changes and let me know if you are ok with them. I will initiate a PR to submit them all upstream after that.

b3ff61c0935b24e9369f3b0058a4985d91678cf8
f2975a95213c0b0d759f706662213782bcd6b45d
1241729b239ca8d0a0c97a68bb6e732a721765dd
3486a5e2f2df5cfb4bd7a4107da6574282cac091
0cc837dc70efe4c48c8475158a87812e85ac2ecc
e84a98556998e37dd7bfc75aba1f231611653542

**Comment by ashuio** [comment]
Thanks for all the work, It all looks good to me.

Please submit a PR whenever you're ready and I'll merge.

**Comment by kiavash-at-work** [comment]
Thanks for accepting the patches. If all is OK, I will close this bug and we can open a new one if needed.
